#!/usr/bin/env fish

set root_dir (status dirname)
find $root_dir/src -name "*.c" | xargs clang-format \
    -style="{BasedOnStyle: llvm, IndentWidth: 4}" \
    -i

find $root_dir/tests -name "*.cc" | xargs clang-format \
    -style="{BasedOnStyle: llvm, IndentWidth: 8}" \
    -i

